In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
obce = pd.read_csv("obce.csv")
obce

,den,datum,kraj_nuts_kod,kraj_nazev,okres_lau_kod,okres_nazev,orp_kod,orp_nazev,obec_kod,obec_nazev,nove_pripady,aktivni_pripady
0,neděle,2020-03-01,CZ041,Karlovarský kraj,CZ0412,Karlovy Vary,4106,Ostrov,554979,Abertamy,0,0
1,pondělí,2020-03-02,CZ041,Karlovarský kraj,CZ0412,Karlovy Vary,4106,Ostrov,554979,Abertamy,0,0
2,úterý,2020-03-03,CZ041,Karlovarský kraj,CZ0412,Karlovy Vary,4106,Ostrov,554979,Abertamy,0,0
3,středa,2020-03-04,CZ041,Karlovarský kraj,CZ0412,Karlovy Vary,4106,Ostrov,554979,Abertamy,0,0
4,čtvrtek,2020-03-05,CZ041,Karlovarský kraj,CZ0412,Karlovy Vary,4106,Ostrov,554979,Abertamy,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2253595,pátek,2021-02-19,CZ020,Středočeský kraj,CZ020B,Příbram,2007,Dobříš,564338,Županovice (Příbram),0,0
2253596,sobota,2021-02-20,CZ020,Středočeský kraj,CZ020B,Příbram,2007,Dobříš,564338,Županovice (Příbram),0,0
2253597,neděle,2021-02-21,CZ020,Středočeský kraj,CZ020B,Příbram,2007,Dobříš,564338,Županovice (Příbram),0,0
2253598,pondělí,2021-02-22,CZ020,Středočeský kraj,CZ020B,Příbram,2007,Dobříš,564338,Županovice (Příbram),0,0
2253599,úterý,2021-02-23,CZ020,Středočeský kraj,CZ020B,Příbram,2007,Dobříš,564338,Županovice (Příbram),0,0

In [4]:
obce.shape

(2253600, 12)

In [5]:
obce.describe()

            orp_kod      obec_kod  nove_pripady  aktivni_pripady
count  2.253600e+06  2.253600e+06  2.253600e+06     2.253600e+06
mean   4.785313e+03  5.619455e+05  5.184997e-01     5.092787e+00
std    1.906843e+03  2.386680e+04  8.457274e+00     7.678464e+01
min    0.000000e+00  5.000110e+05  0.000000e+00     0.000000e+00
25%    3.111000e+03  5.426002e+05  0.000000e+00     0.000000e+00
50%    5.205000e+03  5.635480e+05  0.000000e+00     0.000000e+00
75%    6.404000e+03  5.814550e+05  0.000000e+00     2.000000e+00
max    9.999000e+03  9.999990e+05  2.065000e+03     1.469100e+04

In [6]:
obce.values

array([['neděle', '2020-03-01', 'CZ041', ..., 'Abertamy', 0, 0],
       ['pondělí', '2020-03-02', 'CZ041', ..., 'Abertamy', 0, 0],
       ['úterý', '2020-03-03', 'CZ041', ..., 'Abertamy', 0, 0],
       ...,
       ['neděle', '2021-02-21', 'CZ020', ..., 'Županovice (Příbram)', 0,
        0],
       ['pondělí', '2021-02-22', 'CZ020', ..., 'Županovice (Příbram)', 0,
        0],
       ['úterý', '2021-02-23', 'CZ020', ..., 'Županovice (Příbram)', 0,
        0]], dtype=object)

In [7]:
obce["obec_nazev"]

0                      Abertamy
1                      Abertamy
2                      Abertamy
3                      Abertamy
4                      Abertamy
                   ...
2253595    Županovice (Příbram)
2253596    Županovice (Příbram)
2253597    Županovice (Příbram)
2253598    Županovice (Příbram)
2253599    Županovice (Příbram)
Name: obec_nazev, Length: 2253600, dtype: object

In [20]:
konice = obce[obce["obec_nazev"] == "Konice"]

#df[df['W']>0]

konice
konice.to_excel("Konice_covdi19_pripaddy.xlsx",sheet_name="Sheet1")

budyne = obce[obce["obec_nazev"] == "Budyně nad Ohří"]
budyne.to_excel("Budyne_covid19_pripady.xlsx",sheet_name="Sheet1")
budyne

,den,datum,kraj_nuts_kod,kraj_nazev,okres_lau_kod,okres_nazev,orp_kod,orp_nazev,obec_kod,obec_nazev,nove_pripady,aktivni_pripady
168480,neděle,2020-03-01,CZ042,Ústecký kraj,CZ0423,Litoměřice,4211,Roudnice nad Labem,564656,Budyně nad Ohří,0,0
168481,pondělí,2020-03-02,CZ042,Ústecký kraj,CZ0423,Litoměřice,4211,Roudnice nad Labem,564656,Budyně nad Ohří,0,0
168482,úterý,2020-03-03,CZ042,Ústecký kraj,CZ0423,Litoměřice,4211,Roudnice nad Labem,564656,Budyně nad Ohří,0,0
168483,středa,2020-03-04,CZ042,Ústecký kraj,CZ0423,Litoměřice,4211,Roudnice nad Labem,564656,Budyně nad Ohří,0,0
168484,čtvrtek,2020-03-05,CZ042,Ústecký kraj,CZ0423,Litoměřice,4211,Roudnice nad Labem,564656,Budyně nad Ohří,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
168835,pátek,2021-02-19,CZ042,Ústecký kraj,CZ0423,Litoměřice,4211,Roudnice nad Labem,564656,Budyně nad Ohří,1,15
168836,sobota,2021-02-20,CZ042,Ústecký kraj,CZ0423,Litoměřice,4211,Roudnice nad Labem,564656,Budyně nad Ohří,1,16
168837,neděle,2021-02-21,CZ042,Ústecký kraj,CZ0423,Litoměřice,4211,Roudnice nad Labem,564656,Budyně nad Ohří,0,16
168838,pondělí,2021-02-22,CZ042,Ústecký kraj,CZ0423,Litoměřice,4211,Roudnice nad Labem,564656,Budyně nad Ohří,2,18
168839,úterý,2021-02-23,CZ042,Ústecký kraj,CZ0423,Litoměřice,4211,Roudnice nad Labem,564656,Budyně nad Ohří,0,18

In [9]:
# df['zip'].value_counts().head(5)
obce["obec_nazev"].value_counts().head(100)

Březina (Brno-venkov)           720
Mezholezy (Domažlice)           720
Družec                          360
Bzenec                          360
Skalsko                         360
                               ...
Řehlovice                       360
Uhřice (Blansko)                360
Dětřichov u Moravské Třebové    360
Velká Turná                     360
Adršpach                        360
Name: obec_nazev, Length: 100, dtype: int64

In [10]:
by_obec_nazev = obce.groupby("obec_nazev")

In [11]:
by_obec_nazev.sum()

                           orp_kod   obec_kod  nove_pripady  aktivni_pripady
obec_nazev
Abertamy                   1478160  199792440            65              598
Adamov (Blansko)           2304360  209264760           304             2948
Adamov (Kutná Hora)         721440  191292120            19              184
Adamov (České Budějovice)  1116720  192897360           102             1099
Adršpach                   1872360  197202960            66              640
...                            ...        ...           ...              ...
Žďár nad Sázavou           2273400  214275240          2150            20455
Žďárec                     2310120  214981560            38              366
Žďárek                     1839240  196057440            16              167
Žďárky                     1875240  206889840            79              782
Žďárná                     2304720  209790360            92              903

[6257 rows x 4 columns]

In [12]:
by_obec_nazev.describe()

                          orp_kod                                       \
                            count    mean  std     min     25%     50%
obec_nazev
Abertamy                    360.0  4106.0  0.0  4106.0  4106.0  4106.0
Adamov (Blansko)            360.0  6401.0  0.0  6401.0  6401.0  6401.0
Adamov (Kutná Hora)         360.0  2004.0  0.0  2004.0  2004.0  2004.0
Adamov (České Budějovice)   360.0  3102.0  0.0  3102.0  3102.0  3102.0
Adršpach                    360.0  5201.0  0.0  5201.0  5201.0  5201.0
...                           ...     ...  ...     ...     ...     ...
Žďár nad Sázavou            360.0  6315.0  0.0  6315.0  6315.0  6315.0
Žďárec                      360.0  6417.0  0.0  6417.0  6417.0  6417.0
Žďárek                      360.0  5109.0  0.0  5109.0  5109.0  5109.0
Žďárky                      360.0  5209.0  0.0  5209.0  5209.0  5209.0
Žďárná                      360.0  6402.0  0.0  6402.0  6402.0  6402.0

                                          obec_kod            ...  \
                              75%     max    count      mean  ...
obec_nazev                                                    ...
Abertamy                   4106.0  4106.0    360.0  554979.0  ...
Adamov (Blansko)           6401.0  6401.0    360.0  581291.0  ...
Adamov (Kutná Hora)        2004.0  2004.0    360.0  531367.0  ...
Adamov (České Budějovice)  3102.0  3102.0    360.0  535826.0  ...
Adršpach                   5201.0  5201.0    360.0  547786.0  ...
...                           ...     ...      ...       ...  ...
Žďár nad Sázavou           6315.0  6315.0    360.0  595209.0  ...
Žďárec                     6417.0  6417.0    360.0  597171.0  ...
Žďárek                     5109.0  5109.0    360.0  544604.0  ...
Žďárky                     5209.0  5209.0    360.0  574694.0  ...
Žďárná                     6402.0  6402.0    360.0  582751.0  ...

                          nove_pripady       aktivni_pripady             \
                                   75%   max           count       mean
obec_nazev
Abertamy                           0.0   3.0           360.0   1.661111
Adamov (Blansko)                   1.0  13.0           360.0   8.188889
Adamov (Kutná Hora)                0.0   5.0           360.0   0.511111
Adamov (České Budějovice)          0.0   5.0           360.0   3.052778
Adršpach                           0.0   6.0           360.0   1.777778
...                                ...   ...             ...        ...
Žďár nad Sázavou                   9.0  60.0           360.0  56.819444
Žďárec                             0.0   5.0           360.0   1.016667
Žďárek                             0.0   3.0           360.0   0.463889
Žďárky                             0.0   5.0           360.0   2.172222
Žďárná                             0.0   6.0           360.0   2.508333


                                 std  min  25%   50%    75%    max
obec_nazev
Abertamy                    2.510510  0.0  0.0   0.0   3.00   14.0
Adamov (Blansko)           10.742511  0.0  0.0   1.0  15.00   37.0
Adamov (Kutná Hora)         1.084142  0.0  0.0   0.0   1.00    6.0
Adamov (České Budějovice)   4.557890  0.0  1.0   1.0   3.00   29.0
Adršpach                    3.523191  0.0  0.0   0.0   2.00   20.0
...                              ...  ...  ...   ...    ...    ...
Žďár nad Sázavou           73.029495  0.0  0.0  15.5  97.25  246.0
Žďárec                      2.279801  0.0  0.0   0.0   1.25   15.0
Žďárek                      0.963875  0.0  0.0   0.0   1.00    5.0
Žďárky                      3.530733  0.0  0.0   0.0   3.00   15.0
Žďárná                      4.547482  0.0  0.0   0.0   3.00   22.0

[6257 rows x 32 columns]

In [13]:
obce.head

<bound method NDFrame.head of              den       datum kraj_nuts_kod        kraj_nazev okres_lau_kod  \
0         neděle  2020-03-01         CZ041  Karlovarský kraj        CZ0412
1        pondělí  2020-03-02         CZ041  Karlovarský kraj        CZ0412
2          úterý  2020-03-03         CZ041  Karlovarský kraj        CZ0412
3         středa  2020-03-04         CZ041  Karlovarský kraj        CZ0412
4        čtvrtek  2020-03-05         CZ041  Karlovarský kraj        CZ0412
...          ...         ...           ...               ...           ...
2253595    pátek  2021-02-19         CZ020  Středočeský kraj        CZ020B
2253596   sobota  2021-02-20         CZ020  Středočeský kraj        CZ020B
2253597   neděle  2021-02-21         CZ020  Středočeský kraj        CZ020B
2253598  pondělí  2021-02-22         CZ020  Středočeský kraj        CZ020B
2253599    úterý  2021-02-23         CZ020  Středočeský kraj        CZ020B

          okres_nazev  orp_kod orp_nazev  obec_kod            obec_nazev  \
0        Karlovy Vary     4106    Ostrov    554979              Abertamy
1        Karlovy Vary     4106    Ostrov    554979              Abertamy
2        Karlovy Vary     4106    Ostrov    554979              Abertamy
3        Karlovy Vary     4106    Ostrov    554979              Abertamy
4        Karlovy Vary     4106    Ostrov    554979              Abertamy
...               ...      ...       ...       ...                   ...
2253595       Příbram     2007    Dobříš    564338  Županovice (Příbram)
2253596       Příbram     2007    Dobříš    564338  Županovice (Příbram)
2253597       Příbram     2007    Dobříš    564338  Županovice (Příbram)
2253598       Příbram     2007    Dobříš    564338  Županovice (Příbram)
2253599       Příbram     2007    Dobříš    564338  Županovice (Příbram)

         nove_pripady  aktivni_pripady
0                   0                0
1                   0                0
2                   0                0
3                   0                0
4                   0                0
...               ...              ...
2253595             0                0
2253596             0                0
2253597             0                0
2253598             0                0
2253599             0                0

[2253600 rows x 12 columns]>

In [14]:
testy = pd.read_csv("testy.csv")

In [15]:
testy.describe()

,prirustkovy_pocet_testu,kumulativni_pocet_testu,prirustkovy_pocet_prvnich_testu,kumulativni_pocet_prvnich_testu
count,393.000000,3.930000e+02,206.000000,2.060000e+02
mean,13161.229008,1.514291e+06,20311.349515,2.268847e+06
std,12428.094957,1.579201e+06,11334.460310,1.327622e+06
min,0.000000,2.000000e+01,2019.000000,5.278710e+05
25%,4036.000000,2.738900e+05,9422.000000,9.462992e+05
50%,7756.000000,7.617570e+05,19951.000000,2.270577e+06
75%,22777.000000,2.816925e+06,29830.000000,3.367348e+06
max,47498.000000,5.172363e+06,43808.000000,4.708355e+06

In [16]:
testy.head()

,datum,prirustkovy_pocet_testu,kumulativni_pocet_testu,prirustkovy_pocet_prvnich_testu,kumulativni_pocet_prvnich_testu
0,2020-01-27,20,20,NaN,NaN
1,2020-01-28,8,28,NaN,NaN
2,2020-01-29,5,33,NaN,NaN
3,2020-01-30,1,34,NaN,NaN
4,2020-01-31,3,37,NaN,NaN